export const legalPages = {
  impressum: { title: 'Impressum', description: 'Betreiber und Kontakt von Kaufgeist.', html: `
    <h1>Impressum</h1><h2>Angaben gemäß § 5 DDG</h2>
    <p>Karl Kari<br>Bahnhofstr. 1<br>70173 Stuttgart<br>Deutschland</p>
    <h2>Kontakt</h2><p><a href="mailto:kontakt@kaufgeist.de">kontakt@kaufgeist.de</a></p>
    <h2>Verantwortlich für den Inhalt</h2><p>Karl Kari, Anschrift wie oben.</p>
    <h2>Über die Beratung</h2><p>Kaufgeist bietet eine automatisierte Orientierung bei der Produktauswahl, verkauft aber selbst keine Produkte. Kaufverträge kommen gegebenenfalls beim jeweiligen Händler zustande. Kaufgeist führt keine eigenen Labortests durch und bietet keinen vollständigen Markt- oder Preisvergleich.</p>
    <p><a href="/transparenz">Mehr zu Arbeitsweise und Finanzierung</a></p>` },
  transparenz: { title: 'Über Kaufgeist und Finanzierung', description: 'Wer hinter Kaufgeist steht, wie die Beratung entsteht und welche Grenzen sie hat.', html: `
    <h1>Kaufentscheidungen verständlicher machen.</h1>
    <p>Kaufgeist ist ein Angebot von Karl Kari. Die Idee: Deine Anforderungen stehen zuerst – daraus entsteht eine kurze Auswahl mit verständlichen Kompromissen statt einer langen Produktliste.</p>
    <h2>Wie die Empfehlungen entstehen</h2><ol><li>Du beschreibst Einsatzzweck, Budget und Pflichtmerkmale.</li><li>Die KI recherchiert Webquellen und ordnet geeignete Modellreihen ein.</li><li>Du erhältst bis zu drei Optionen mit Gründen, Nachteilen und offenen Prüfpunkten.</li><li>Über eine gezielte Amazon-Suche kannst du konkrete Varianten selbst kontrollieren.</li></ol>
    <h2>Was wir nicht versprechen</h2><p>Wir führen keine eigenen Labortests durch. Eine KI-Recherche ist keine lückenlose Marktprüfung. Recherchebelege stützen die Einordnung, garantieren aber keine fehlerfreie Aussage. Herstellerangaben und unabhängige Tests sind unterschiedlich zu bewerten.</p><p>Ein Modellvorschlag ist kein geprüftes Angebot. Preis, Ausstattung, Händler, Zustand und Verfügbarkeit müssen vor dem Kauf geprüft werden. Wir zeigen keine ungeprüften Händlerpreise oder Sternebewertungen.</p>
    <h2>Finanzierung im Aufbau</h2><p>Die Beratung ist kostenlos und ohne Registrierung nutzbar. Für die Zukunft ist eine Finanzierung über gekennzeichnete Affiliate-Links geplant. Aktuell ist Kaufgeist noch nicht für Amazon PartnerNet zugelassen. Die Amazon-Suchlinks sind normale Links, über die Kaufgeist keine Partnerprovision erhält.</p><p>Wir werden eine spätere Partnerteilnahme und provisionsfähige Links klar kennzeichnen. Amazon unterstützt oder empfiehlt Kaufgeist damit nicht. Die Höhe einer möglichen Provision soll kein Auswahlkriterium sein.</p>
    <h2>Fehler melden</h2><p>Eine Empfehlung passt nicht? Schreibe uns unter <a href="mailto:kontakt@kaufgeist.de">kontakt@kaufgeist.de</a>. Bitte sende keine sensiblen persönlichen Informationen mit.</p>` },
  datenschutz: { title: 'Datenschutz', description: 'Informationen zur Verarbeitung von Daten bei Kaufgeist und zu Einstellungen der Reichweitenmessung.', html: `
    <h1>Datenschutzhinweise</h1><p>Stand: 3. Oktober 2026</p>
    <h2>1. Verantwortlicher und Kontakt</h2><p>Karl Kari, Bahnhofstr. 1, 70173 Stuttgart, Deutschland. E-Mail: <a href="mailto:kontakt@kaufgeist.de">kontakt@kaufgeist.de</a>.</p>
    <h2>2. Website und Hosting</h2><p>Die Website wird mit Vercel bereitgestellt. Beim Abruf werden insbesondere IP-Adresse, Zeitpunkt, aufgerufene Adresse und technische Browserinformationen zur Auslieferung, Fehleranalyse und Absicherung verarbeitet. Grundlage ist unser berechtigtes Interesse an einem sicheren, funktionsfähigen Angebot (Art. 6 Abs. 1 lit. f DSGVO). Technische Dienstleister können Verbindungs- und Sicherheitsprotokolle nach ihren vertraglichen Einstellungen speichern.</p>
    <h2>3. KI-Beratung und Webrecherche</h2><p>Wenn du eine Beratung startest, übermitteln wir deine Eingabe und einen begrenzten Teil des aktuellen Chatverlaufs an die OpenAI-API. Teile deiner Produktanfrage können für eine Websuche verarbeitet werden. Dies dient der von dir angeforderten Beratung (Art. 6 Abs. 1 lit. b DSGVO). Gib keine Namen, Adressen, Passwörter, Gesundheitsdaten oder andere sensible Angaben ein.</p><p>Der Chatverlauf wird im Arbeitsspeicher deines Browsers gehalten und mit einem neuen Chat oder dem Neuladen verworfen. Kaufgeist legt keine Anfragen oder Antworten in seiner Datenbank ab. Wir setzen bei der API <code>store: false</code>; dies schließt Sicherheitsprotokolle des Dienstleisters nicht aus. OpenAI beschreibt die Verarbeitung und Aufbewahrung unter <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noopener noreferrer">API-Datenschutz und Aufbewahrung</a>. Daten aus der API werden nach OpenAIs Standardbedingungen nicht ohne ausdrückliche Freigabe zum Modelltraining genutzt.</p>
    <h2>4. Schutz vor Missbrauch</h2><p>Für Zugriffslimits verarbeiten wir einen täglich wechselnden, mit einem geheimen Schlüssel abgeleiteten Wert aus der IP-Adresse sowie Anfragezähler über Supabase. Die ursprüngliche IP-Adresse und Chattexte werden nicht in diesen Zählern gespeichert. Die Werte bleiben personenbezogene beziehungsweise pseudonymisierte Daten. Grundlage ist Art. 6 Abs. 1 lit. f DSGVO: Schutz vor Missbrauch und unverhältnismäßigen Betriebskosten.</p><p>Zähler gelten für ein kurzes Zeitfenster beziehungsweise bis zum Ende des UTC-Tages. Abgelaufene Einträge werden beim nächsten Beratungsaufruf entfernt. Für die Zähler wird kein Werbeprofil erstellt.</p>
    <h2>5. Freiwillige Reichweiten- und Werbemessung</h2><p>Nur nach deiner Einwilligung laden wir Google Ads und, soweit eingerichtet, Google Analytics. Dabei können Cookie-Kennungen, technische Geräteinformationen, Seitenaufrufe und Ereignisse wie Beratungsstart, angezeigte Empfehlungen oder ein Klick auf die Amazon-Suche verarbeitet werden. Chattexte, Produktnamen und Inhalte deiner Anfragen senden wir nicht als Messereignisse. Ein Amazon-Klick ist kein Nachweis eines Kaufs. Personalisierte Werbung und Google Signals sind in unserer Implementierung deaktiviert.</p><p>Grundlage ist deine Einwilligung (Art. 6 Abs. 1 lit. a DSGVO; für einwilligungspflichtige Zugriffe auf dein Endgerät § 25 Abs. 1 TDDDG). Empfänger ist insbesondere Google Ireland Limited; weitere Informationen: <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">Wie Google Daten von Partner-Websites verwendet</a>.</p><p>Die Auswahl wird mit Zeitpunkt und Hinweisversion bis zu 180 Tage lokal gespeichert. Du kannst sie jederzeit über <button class="tag-btn" onclick="showConsentBanner()">Cookie-Einstellungen</button> ändern. Ein Widerruf lädt die Seite neu, verwirft den offenen Chat und stoppt die Messung für zukünftige Vorgänge. Bereits rechtmäßig verarbeitete Daten bleiben davon unberührt. Die Beratung funktioniert auch ohne Einwilligung.</p>
    <h2>6. Links zu Amazon und Recherchequellen</h2><p>Erst wenn du einen externen Link öffnest, rufst du die betreffende Website auf. Dort gelten die Hinweise des jeweiligen Betreibers. Aktuell verwenden wir normale Amazon-Suchlinks ohne Partner-ID. Es findet kein Abruf von Amazon-Angebotsdaten über RapidAPI statt.</p>
    <h2>7. Kontaktaufnahme</h2><p>Wenn du uns per E-Mail kontaktierst, verarbeiten wir deine Angaben zur Bearbeitung der Anfrage (Art. 6 Abs. 1 lit. b oder f DSGVO, je nach Anliegen). Wir bewahren sie nur so lange auf, wie dies für die Bearbeitung oder gesetzliche Aufbewahrungspflichten erforderlich ist.</p>
    <h2>8. Dienstleister und internationale Verarbeitung</h2><p>Wir nutzen Vercel für Hosting, OpenAI für die Beratung, Supabase für Missbrauchsschutz und nach Einwilligung Google für Messung. Bei diesen Diensten kann eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums, insbesondere in den USA, stattfinden. Maßgeblich sind die jeweiligen Auftragsverarbeitungsvereinbarungen und anwendbaren Übermittlungsgrundlagen, etwa ein Angemessenheitsbeschluss oder Standardvertragsklauseln.</p><p><strong>Hinweis zum Einrichtungsstand:</strong> Die konkreten Projektregionen, Dienstleister-Vertragsdaten und Aufbewahrungsfristen technischer Dienstleister müssen vor einer Werbekampagne durch den Betreiber abschließend geprüft und hier ergänzt werden. Diese Hinweise sind keine Bestätigung einer abgeschlossenen rechtlichen Prüfung.</p>
    <h2>9. Deine Rechte</h2><p>Du hast nach den gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit sowie Widerspruch gegen eine Verarbeitung auf Basis berechtigter Interessen. Einwilligungen kannst du jederzeit für die Zukunft widerrufen. Du kannst dich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere beim Landesbeauftragten für den Datenschutz und die Informationsfreiheit Baden-Württemberg. Für Anfragen nutze bitte die oben genannte E-Mail-Adresse.</p>` },
};

export const landingPages = {
  'office-laptop': {
    title: 'Office-Laptop auswählen: kostenlose KI-Kaufberatung',
    headline: 'Welcher Laptop passt zu deinem Arbeitsalltag?',
    lead: 'Office, Studium oder Videokonferenzen: Beschreibe dein Budget und deine Anforderungen. Wir helfen dir, Modellreihen und Kompromisse einzuordnen.',
    placeholder: 'Z. B. Windows-Laptop bis 700 €, Office, 16 GB RAM',
    question: '„Ein Laptop fürs Homeoffice – ohne unnötige Gaming-Ausstattung.“',
    guide: '<li><strong>Programme:</strong> Browser und Office stellen andere Anforderungen als CAD oder Videoschnitt.</li><li><strong>Arbeitsplatz:</strong> Unterwegs zählen Gewicht und Akku; am Schreibtisch eher Anschlüsse, Tastatur und Monitor.</li><li><strong>Gesamtbudget:</strong> Betriebssystem, Dock und Zubehör mitdenken. Ausstattungsvarianten derselben Modellreihe können sich deutlich unterscheiden.</li>',
    quick: [['Office bis 700 €', 'Ich suche einen neuen Windows-Laptop bis 700 Euro für Office und Videokonferenzen, mindestens 16 GB RAM und 512 GB SSD.'], ['Leicht fürs Studium', 'Ich suche einen leichten Laptop fürs Studium. Welche Angaben brauchst du für eine Auswahl?']],
  },
  kaffeevollautomat: {
    title: 'Kaffeevollautomat auswählen: kostenlose KI-Kaufberatung',
    headline: 'Welcher Kaffeevollautomat passt zu deinem Alltag?',
    lead: 'Espresso oder Cappuccino, eine Tasse oder die ganze Familie: Finde heraus, welche Funktionen sich für dich lohnen – und welche nicht.',
    placeholder: 'Z. B. bis 500 €, zwei Personen, oft Cappuccino',
    question: '„Cappuccino für zwei – möglichst wenig Reinigungsaufwand.“',
    guide: '<li><strong>Getränke:</strong> Wer überwiegend schwarzen Kaffee trinkt, braucht nicht zwingend ein automatisches Milchsystem.</li><li><strong>Pflege:</strong> Milchleitungen, Brühgruppe und Entkalkung bestimmen den Aufwand im Alltag.</li><li><strong>Folgekosten:</strong> Filter, Reiniger und Verschleißteile zusätzlich zum Kaufpreis berücksichtigen.</li>',
    quick: [['Für zwei bis 500 €', 'Ich suche einen neuen Kaffeevollautomaten bis 500 Euro für zwei Personen, häufig Cappuccino. Einfache Reinigung ist besonders wichtig.'], ['Vor allem schwarzer Kaffee', 'Ich suche einen Kaffeevollautomaten für überwiegend schwarzen Kaffee. Welche Angaben brauchst du für die Auswahl?']],
  },
};
